name: windows-build-test

on:
  pull_request:
  push:
    branches:
      - master
      - dev
      - ci-build-windows
    tags:
      - v*

defaults:
  run:
    shell: bash

jobs:
  #
  # Produce a "full" source-archive, that is, including source from submodules
  #
  # This is done to provide the source-archive for users in environments without
  # submodule access and for the containers in the workflow which does not have
  # a recent enough version of git do pull down the modules
  #
  source-archive-gen:
    runs-on: ubuntu-latest

    steps:
    - name: Grab source
      uses: actions/checkout@v2

    - name: Prepare Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Generate Full Source Archive
      run: |
        sudo ./scripts/pkgs/ubuntu-focal.sh
        make clobber gen-src-archive

    - name: Upload source archive
      uses: actions/upload-artifact@v2
      with:
        name: archive-src
        path: builddir/meson-dist/*.tar.gz


  # Build the source-archive on Windows
  windows-build:
    runs-on: ${{ matrix.runner.os }}-${{ matrix.runner.ver }}
    needs: source-archive-gen

    strategy:
      matrix:
        runner:
          - { os: 'windows', ver: '2019' }
          - { os: 'windows', ver: '2022' }

    steps:
    - name: Image-prep, get the full-source-archive
      uses: actions/download-artifact@v2
      with:
        name: archive-src

    - name: Unpack the full-source-archive
      run: |
        tar xzf xnvme*.tar.gz --strip 1
        rm xnvme*.tar.gz

    - name: Install build-requirements
      run: |
        cmd.exe /c "echo %cd%"
        cmd.exe /c "scripts\pkgs\${{ matrix.runner.os }}-${{ matrix.runner.ver }}.bat"

    - name: Build!
      run: |
        cmd.exe /c "build.bat"

    - name: Dump the compile-commands and machine
      run: |
        cat /proc/cpuinfo || true
        cat builddir/compile_commands.json || true

    - name: Install
      shell: cmd
      run: |
        cmd.exe /c "build.bat install"

    - name: Execute xnvme commands
      shell: cmd
      run: |
        set "PATH=%SystemDrive%\tools\msys64;!PATH!"
        set "PATH=%SystemDrive%\tools\msys64\mingw64\bin;!PATH!"

        xnvme.exe enum
        xnvme.exe library-info
